FROM tykio/tyk-gateway:v4.1rc26
COPY deployments/tyk-gateway /opt/tyk-gateway/deployments/tyk-gateway
COPY entrypoint.sh /opt/tyk-gateway
RUN ["chmod", "+x", "./entrypoint.sh"]
EXPOSE 8080
ENTRYPOINT [""]
#CMD export TYK_GW_LISTENPORT=$PORT; env; ./tyk start --conf=./deployments/tyk-gateway/tyk.conf
CMD ./entrypoint.sh; ./tyk start --conf=./deployments/tyk-gateway/tyk.conf